"""
Automated 52/52 Train/Serve Feature Parity Test Suite for Lakers in 5.
Validates that every single feature generated in historical training is mathematically
and semantically identical to the features generated by ProductionFeatureService.
"""

import pytest
import numpy as np
import pandas as pd
from src.lake.duckdb_client import DuckDBClient
from src.inference.feature_service import ProductionFeatureService, MODEL_FEATURE_CONTRACT

@pytest.fixture(scope="module")
def lake_client():
    return DuckDBClient()

@pytest.fixture(scope="module")
def prod_feature_service(lake_client):
    return ProductionFeatureService(duckdb_client=lake_client)

@pytest.fixture(scope="module")
def training_features_df():
    return pd.read_parquet("data/features/game_features.parquet")


def test_contract_column_count_and_order():
    """Verify MODEL_FEATURE_CONTRACT contains exactly 52 unique features."""
    assert len(MODEL_FEATURE_CONTRACT) == 52
    assert len(set(MODEL_FEATURE_CONTRACT)) == 52


def test_historical_train_serve_parity_52_features(training_features_df, prod_feature_service):
    """
    Test that across sampled historical games (varying seasons, home/away franchises),
    ProductionFeatureService produces exact (within tolerance) feature vectors matching training.
    """
    # Sample games across recent seasons (2021 to 2025)
    sample_games = training_features_df[
        (training_features_df["season"] >= 2021) &
        (training_features_df["home_team_id"].isin(["1610612747", "1610612744", "1610612738", "1610612748", "1610612752"]))
    ].sample(20, random_state=42)
    
    exact_match_cols = [
        "home_elo", "away_elo", "elo_difference",
        "home_rest_days", "away_rest_days", "rest_difference",
        "home_back_to_back", "away_back_to_back",
        "home_games_last_7", "away_games_last_7"
    ]
    
    floating_point_cols = [c for c in MODEL_FEATURE_CONTRACT if c not in exact_match_cols]
    
    total_comparisons = 0
    mismatches = []
    
    for idx, row in sample_games.iterrows():
        game_id = row["game_id"]
        game_date = str(row["game_date"])[:10]
        home_id = str(row["home_team_id"])
        away_id = str(row["away_team_id"])
        
        prod_feat_df = prod_feature_service.generate_pregame_feature_vector(
            home_team_identifier=home_id,
            away_team_identifier=away_id,
            target_game_date=game_date
        )
        
        # Verify schema
        assert list(prod_feat_df.columns) == MODEL_FEATURE_CONTRACT
        
        for col in MODEL_FEATURE_CONTRACT:
            total_comparisons += 1
            train_val = row[col]
            prod_val = prod_feat_df[col].iloc[0]
            
            if pd.isna(train_val) and pd.isna(prod_val):
                continue
            elif pd.isna(train_val) != pd.isna(prod_val):
                mismatches.append(f"Game {game_id} ({game_date}) Col '{col}': Train={train_val}, Prod={prod_val} (NaN mismatch)")
            elif col in exact_match_cols:
                if not np.isclose(train_val, prod_val, atol=1e-5):
                    mismatches.append(f"Game {game_id} ({game_date}) Exact Col '{col}': Train={train_val}, Prod={prod_val}")
            else:
                if not np.isclose(train_val, prod_val, atol=1e-5):
                    mismatches.append(f"Game {game_id} ({game_date}) Float Col '{col}': Train={train_val}, Prod={prod_val} (diff={abs(train_val - prod_val)})")
                    
    assert len(mismatches) == 0, f"Found {len(mismatches)} mismatches out of {total_comparisons} checks:\n" + "\n".join(mismatches[:10])
