-- =============================================================================
-- Lakers in 5 — Relational Database Schema DDL (01_create_tables.sql)
-- Target RDBMS: PostgreSQL (Neon Serverless Postgres)
-- =============================================================================

-- Drop tables in reverse topological order if resetting
DROP TABLE IF EXISTS player_game_stats_extended CASCADE;
DROP TABLE IF EXISTS player_game_stats CASCADE;
DROP TABLE IF EXISTS team_game_stats_extended CASCADE;
DROP TABLE IF EXISTS team_game_stats CASCADE;
DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS team_histories CASCADE;

-- 1. TEAMS (Canonical Dimension Table)
CREATE TABLE teams (
    team_id BIGINT PRIMARY KEY,
    team_abbreviation VARCHAR(20),
    team_city VARCHAR(100) NOT NULL,
    team_name VARCHAR(100) NOT NULL,
    season_founded INTEGER,
    season_active_till VARCHAR(50),
    league VARCHAR(100) DEFAULT 'NBA'
);

-- 2. PLAYERS (Player Bio Dimension Table)
CREATE TABLE players (
    person_id BIGINT PRIMARY KEY,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    birth_date DATE,
    school VARCHAR(150),
    country VARCHAR(100),
    height_inches INTEGER,
    body_weight_lbs INTEGER,
    jersey VARCHAR(20),
    is_guard BOOLEAN DEFAULT FALSE,
    is_forward BOOLEAN DEFAULT FALSE,
    is_center BOOLEAN DEFAULT FALSE,
    draft_year INTEGER,
    draft_round INTEGER,
    draft_number INTEGER,
    from_year INTEGER,
    to_year INTEGER
);

-- 3. GAMES (Game-Level Matchups & Ground Truth Targets)
CREATE TABLE games (
    game_id VARCHAR(50) PRIMARY KEY,
    game_datetime_est TIMESTAMP,
    game_date DATE,
    home_team_id BIGINT REFERENCES teams(team_id),
    home_team_city VARCHAR(100),
    home_team_name VARCHAR(100),
    away_team_id BIGINT REFERENCES teams(team_id),
    away_team_city VARCHAR(100),
    away_team_name VARCHAR(100),
    home_score INTEGER,
    away_score INTEGER,
    winner VARCHAR(100),
    game_type VARCHAR(50),
    game_subtype VARCHAR(50),
    game_label VARCHAR(100),
    game_sub_label VARCHAR(100),
    series_game_number INTEGER,
    attendance INTEGER,
    arena_id VARCHAR(50),
    arena_name VARCHAR(150),
    arena_city VARCHAR(100),
    arena_state VARCHAR(50),
    officials TEXT
);

-- 4. TEAM_GAME_STATS (Traditional Box Score Per Team-Game)
CREATE TABLE team_game_stats (
    game_id VARCHAR(50) NOT NULL REFERENCES games(game_id),
    team_id BIGINT NOT NULL REFERENCES teams(team_id),
    game_datetime_est TIMESTAMP,
    game_date DATE,
    team_city VARCHAR(100),
    team_name VARCHAR(100),
    opponent_team_id BIGINT REFERENCES teams(team_id),
    opponent_team_city VARCHAR(100),
    opponent_team_name VARCHAR(100),
    home INTEGER NOT NULL,
    win INTEGER NOT NULL,
    team_score INTEGER,
    opponent_score INTEGER,
    assists INTEGER,
    blocks INTEGER,
    steals INTEGER,
    field_goals_attempted INTEGER,
    field_goals_made INTEGER,
    field_goals_percentage DOUBLE PRECISION,
    three_pointers_attempted INTEGER,
    three_pointers_made INTEGER,
    three_pointers_percentage DOUBLE PRECISION,
    free_throws_attempted INTEGER,
    free_throws_made INTEGER,
    free_throws_percentage DOUBLE PRECISION,
    rebounds_defensive INTEGER,
    rebounds_offensive INTEGER,
    rebounds_total INTEGER,
    rebounds_team INTEGER,
    fouls_personal INTEGER,
    turnovers INTEGER,
    turnovers_team INTEGER,
    plus_minus_points INTEGER,
    num_minutes DOUBLE PRECISION,
    q1_points INTEGER,
    q2_points INTEGER,
    q3_points INTEGER,
    q4_points INTEGER,
    ot1_points INTEGER,
    ot2_points INTEGER,
    ot_all_points INTEGER,
    bench_points INTEGER,
    biggest_lead INTEGER,
    biggest_scoring_run INTEGER,
    lead_changes INTEGER,
    points_fast_break INTEGER,
    points_from_turnovers INTEGER,
    points_in_the_paint INTEGER,
    points_second_chance INTEGER,
    times_tied INTEGER,
    timeouts_remaining INTEGER,
    season_wins INTEGER,
    season_losses INTEGER,
    coach_id VARCHAR(50),
    game_type VARCHAR(50),
    game_label VARCHAR(100),
    game_sub_label VARCHAR(100),
    series_game_number INTEGER,
    seed INTEGER,
    PRIMARY KEY (game_id, team_id)
);

-- 5. TEAM_GAME_STATS_EXTENDED (Advanced & Tracking Metrics Per Team-Game)
CREATE TABLE team_game_stats_extended (
    game_id VARCHAR(50) NOT NULL REFERENCES games(game_id),
    team_id BIGINT NOT NULL REFERENCES teams(team_id),
    game_datetime_est TIMESTAMP,
    game_type VARCHAR(50),
    game_label VARCHAR(100),
    game_sub_label VARCHAR(100),
    series_game_number INTEGER,
    team_city VARCHAR(100),
    team_name VARCHAR(100),
    opponent_team_id BIGINT REFERENCES teams(team_id),
    opponent_team_city VARCHAR(100),
    opponent_team_name VARCHAR(100),
    home INTEGER,
    win INTEGER,
    team_score INTEGER,
    opponent_score INTEGER,
    seed INTEGER,
    num_minutes DOUBLE PRECISION,
    offensive_rating DOUBLE PRECISION,
    estimated_offensive_rating DOUBLE PRECISION,
    defensive_rating DOUBLE PRECISION,
    estimated_defensive_rating DOUBLE PRECISION,
    net_rating DOUBLE PRECISION,
    estimated_net_rating DOUBLE PRECISION,
    assist_percentage DOUBLE PRECISION,
    assist_to_turnover_ratio DOUBLE PRECISION,
    assist_ratio DOUBLE PRECISION,
    offensive_rebound_percentage DOUBLE PRECISION,
    defensive_rebound_percentage DOUBLE PRECISION,
    rebound_percentage DOUBLE PRECISION,
    team_turnover_percentage DOUBLE PRECISION,
    effective_field_goal_percentage DOUBLE PRECISION,
    true_shooting_percentage DOUBLE PRECISION,
    pace DOUBLE PRECISION,
    estimated_pace DOUBLE PRECISION,
    pace_per40 DOUBLE PRECISION,
    possessions INTEGER,
    player_impact_estimate DOUBLE PRECISION,
    points_off_turnovers DOUBLE PRECISION,
    opponent_points_off_turnovers DOUBLE PRECISION,
    opponent_points_second_chance DOUBLE PRECISION,
    opponent_points_fast_break DOUBLE PRECISION,
    opponent_points_in_paint DOUBLE PRECISION,
    percent_field_goal_attempts_2point DOUBLE PRECISION,
    percent_field_goal_attempts_3point DOUBLE PRECISION,
    percent_points_2point DOUBLE PRECISION,
    percent_points_2point_mid_range DOUBLE PRECISION,
    percent_points_3point DOUBLE PRECISION,
    percent_points_fast_break DOUBLE PRECISION,
    percent_points_free_throw DOUBLE PRECISION,
    percent_points_off_turnovers DOUBLE PRECISION,
    percent_points_in_paint DOUBLE PRECISION,
    percent_assisted_2point_made DOUBLE PRECISION,
    percent_unassisted_2point_made DOUBLE PRECISION,
    percent_assisted_3point_made DOUBLE PRECISION,
    percent_unassisted_3point_made DOUBLE PRECISION,
    percent_assisted_field_goals_made DOUBLE PRECISION,
    percent_unassisted_field_goals_made DOUBLE PRECISION,
    free_throw_attempt_rate DOUBLE PRECISION,
    opponent_effective_field_goal_percentage DOUBLE PRECISION,
    opponent_free_throw_attempt_rate DOUBLE PRECISION,
    opponent_turnover_percentage DOUBLE PRECISION,
    opponent_offensive_rebound_percentage DOUBLE PRECISION,
    PRIMARY KEY (game_id, team_id)
);

-- 6. PLAYER_GAME_STATS (Individual Player Box Scores)
CREATE TABLE player_game_stats (
    game_id VARCHAR(50) NOT NULL REFERENCES games(game_id),
    person_id BIGINT NOT NULL REFERENCES players(person_id),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    game_datetime_est TIMESTAMP,
    game_date DATE,
    player_team_id BIGINT REFERENCES teams(team_id),
    player_team_city VARCHAR(100),
    player_team_name VARCHAR(100),
    opponent_team_id BIGINT REFERENCES teams(team_id),
    opponent_team_city VARCHAR(100),
    opponent_team_name VARCHAR(100),
    game_type VARCHAR(50),
    game_label VARCHAR(100),
    game_sub_label VARCHAR(100),
    series_game_number INTEGER,
    win INTEGER,
    home INTEGER,
    num_minutes VARCHAR(20),
    points INTEGER,
    assists INTEGER,
    blocks INTEGER,
    steals INTEGER,
    field_goals_attempted INTEGER,
    field_goals_made INTEGER,
    field_goals_percentage DOUBLE PRECISION,
    three_pointers_attempted INTEGER,
    three_pointers_made INTEGER,
    three_pointers_percentage DOUBLE PRECISION,
    free_throws_attempted INTEGER,
    free_throws_made INTEGER,
    free_throws_percentage DOUBLE PRECISION,
    rebounds_defensive INTEGER,
    rebounds_offensive INTEGER,
    rebounds_total INTEGER,
    fouls_personal INTEGER,
    turnovers INTEGER,
    plus_minus_points INTEGER,
    comment TEXT,
    starting_position VARCHAR(10),
    PRIMARY KEY (game_id, person_id)
);

-- 7. PLAYER_GAME_STATS_EXTENDED (Advanced Player Tracking & Impact Metrics)
CREATE TABLE player_game_stats_extended (
    game_id VARCHAR(50) NOT NULL REFERENCES games(game_id),
    person_id BIGINT NOT NULL REFERENCES players(person_id),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    game_datetime_est TIMESTAMP,
    game_type VARCHAR(50),
    game_label VARCHAR(100),
    game_sub_label VARCHAR(100),
    series_game_number INTEGER,
    win INTEGER,
    home INTEGER,
    player_team_id BIGINT REFERENCES teams(team_id),
    player_team_city VARCHAR(100),
    player_team_name VARCHAR(100),
    opponent_team_id BIGINT REFERENCES teams(team_id),
    opponent_team_city VARCHAR(100),
    opponent_team_name VARCHAR(100),
    comment TEXT,
    starting_position VARCHAR(10),
    num_minutes DOUBLE PRECISION,
    points INTEGER,
    assists INTEGER,
    rebounds_total INTEGER,
    rebounds_offensive INTEGER,
    rebounds_defensive INTEGER,
    field_goals_made INTEGER,
    field_goals_attempted INTEGER,
    field_goals_percentage DOUBLE PRECISION,
    three_pointers_made INTEGER,
    three_pointers_attempted INTEGER,
    three_pointers_percentage DOUBLE PRECISION,
    free_throws_made INTEGER,
    free_throws_attempted INTEGER,
    free_throws_percentage DOUBLE PRECISION,
    steals INTEGER,
    blocks INTEGER,
    blocks_against INTEGER,
    turnovers INTEGER,
    fouls_personal INTEGER,
    fouls_against INTEGER,
    plus_minus_points INTEGER,
    double_double INTEGER,
    triple_double INTEGER,
    offensive_rating DOUBLE PRECISION,
    estimated_offensive_rating DOUBLE PRECISION,
    defensive_rating DOUBLE PRECISION,
    estimated_defensive_rating DOUBLE PRECISION,
    net_rating DOUBLE PRECISION,
    estimated_net_rating DOUBLE PRECISION,
    assist_percentage DOUBLE PRECISION,
    assist_to_turnover_ratio DOUBLE PRECISION,
    assist_ratio DOUBLE PRECISION,
    offensive_rebound_percentage DOUBLE PRECISION,
    defensive_rebound_percentage DOUBLE PRECISION,
    rebound_percentage DOUBLE PRECISION,
    team_turnover_percentage DOUBLE PRECISION,
    estimated_turnover_percentage DOUBLE PRECISION,
    effective_field_goal_percentage DOUBLE PRECISION,
    true_shooting_percentage DOUBLE PRECISION,
    usage_percentage DOUBLE PRECISION,
    estimated_usage_percentage DOUBLE PRECISION,
    pace DOUBLE PRECISION,
    estimated_pace DOUBLE PRECISION,
    pace_per40 DOUBLE PRECISION,
    player_impact_estimate DOUBLE PRECISION,
    possessions INTEGER,
    points_off_turnovers DOUBLE PRECISION,
    points_second_chance DOUBLE PRECISION,
    points_fast_break DOUBLE PRECISION,
    points_in_paint DOUBLE PRECISION,
    percent_team_points DOUBLE PRECISION,
    percent_team_assists DOUBLE PRECISION,
    percent_team_rebounds DOUBLE PRECISION,
    percent_team_turnovers DOUBLE PRECISION,
    percent_team_steals DOUBLE PRECISION,
    percent_team_blocks DOUBLE PRECISION,
    percent_assisted_2point_made DOUBLE PRECISION,
    percent_unassisted_2point_made DOUBLE PRECISION,
    percent_assisted_3point_made DOUBLE PRECISION,
    percent_unassisted_3point_made DOUBLE PRECISION,
    percent_assisted_field_goals_made DOUBLE PRECISION,
    percent_unassisted_field_goals_made DOUBLE PRECISION,
    PRIMARY KEY (game_id, person_id)
);

-- 8. TRANSACTIONS (2026 Offseason Roster Moves)
CREATE TABLE transactions (
    id SERIAL PRIMARY KEY,
    team VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    player VARCHAR(150) NOT NULL,
    transaction_details TEXT,
    status VARCHAR(100)
);

-- 9. TEAM_HISTORIES (Franchise Lineage & Relocation History)
CREATE TABLE team_histories (
    id SERIAL PRIMARY KEY,
    team_id BIGINT NOT NULL,
    team_city VARCHAR(100) NOT NULL,
    team_name VARCHAR(100) NOT NULL,
    team_abbrev VARCHAR(20),
    season_founded INTEGER,
    season_active_till VARCHAR(50),
    league VARCHAR(100)
);
